---

- name: run initial ubuntu setup
  hosts: localhost
  become: yes
  tasks:

  - name: ensure aptitude is installed
    command: apt-get -y install aptitude
    args:
        warn: false

  - name: update the apt package index
    apt: update_cache=yes

  - name: upgrade system packages
    apt: upgrade=yes
